before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip -O packer.zip && unzip -d packer packer.zip
before_script: export PATH=$PATH:$PWD/packer
script: make validate
notifications:
  email: false
